import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0a0f1f',
    padding: 18,
    alignItems: 'center',
  },
  scrollContainer: {
    backgroundColor: '#0a0f1f',
    padding: 18,
    gap: 12,
  },
  screen: {
    flex: 1,
    backgroundColor: '#0a0f1f',
  },
  contentWrap: {
    padding: 18,
    gap: 12,
  },
  listWrap: {
    paddingBottom: 24,
    gap: 10,
  },
  titleText: {
    fontSize: 24,
    fontWeight: '700',
    color: '#39ff14',
    textAlign: 'center',
    marginBottom: 6,
    fontFamily: 'monospace',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#00e5ff',
    marginBottom: 6,
    fontFamily: 'monospace',
  },
  bodyText: {
    fontSize: 15,
    lineHeight: 22,
    color: '#d3d9e6',
    fontFamily: 'monospace',
  },
  metaText: {
    fontSize: 12,
    color: '#95a1bd',
    marginTop: 8,
    fontFamily: 'monospace',
  },
  errorText: {
    color: '#ff7676',
    fontSize: 13,
    fontFamily: 'monospace',
  },
  card: {
    backgroundColor: '#111a33',
    borderRadius: 0,
    borderWidth: 2,
    borderColor: '#39ff14',
    padding: 12,
  },
  mainImage: {
    width: '100%',
    height: 220,
    borderRadius: 0,
    borderWidth: 2,
    borderColor: '#00e5ff',
    marginTop: 8,
  },
  detailImage: {
    width: '100%',
    height: 220,
    borderRadius: 0,
    borderWidth: 2,
    borderColor: '#00e5ff',
    marginBottom: 8,
  },
  input: {
    backgroundColor: '#111a33',
    borderWidth: 2,
    borderColor: '#39ff14',
    borderRadius: 0,
    padding: 12,
    fontSize: 15,
    color: '#d3d9e6',
    minHeight: 50,
    fontFamily: 'monospace',
  },
  button: {
    backgroundColor: '#00e5ff',
    borderRadius: 0,
    borderWidth: 2,
    borderColor: '#39ff14',
    paddingVertical: 12,
    alignItems: 'center',
  },
  buttonText: {
    color: '#0a0f1f',
    fontSize: 14,
    fontWeight: '700',
    fontFamily: 'monospace',
    textTransform: 'uppercase',
  },
});
