"""
Author: Alvin Zhu
Email: alvinz@bu.edu
Description: Initial migration creating the Profile table for mini_insta.
"""

# Generated by Django 6.0.1 on 2026-02-13

from django.db import migrations, models


class Migration(migrations.Migration):
    """Create the initial Profile model table for mini_insta."""

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("profile_image_url", models.URLField()),
                ("bio_text", models.TextField()),
                ("join_date", models.DateField()),
            ],
        ),
    ]
